"""criacao inicial

Etapa 4 (Modelagem): cria as cinco tabelas do dominio -- tenants,
usuarios, clientes, servicos, agendamentos -- geradas por
`alembic revision --autogenerate` a partir de app.modelos (SQLModel).

Dois detalhes que o autogenerate nao decide sozinho, e que refletem
decisoes da secao 4.4/4.6 documentadas nos proprios modelos:
  - agendamentos.inicio / agendamentos.fim usam DateTime(timezone=True)
    -> TIMESTAMPTZ no Postgres (tempo sem fuso e ambiguo).
  - o indice composto ix_agendamentos_tenant_intervalo, sobre
    (tenant_id, inicio, fim), existe para a pergunta de conflito de
    horario que a Etapa 5 vai fazer.

Revision ID: 4daf712f87bb
Revises:
Create Date: 2026-07-20 20:29:13.384273

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4daf712f87bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_tenant_id'), 'clientes', ['tenant_id'], unique=False)
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_tenant_id'), 'servicos', ['tenant_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('papel', sa.Enum('DONO', 'ATENDENTE', name='papel'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_tenant_id'), 'usuarios', ['tenant_id'], unique=False)
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_tenant_id'), 'agendamentos', ['tenant_id'], unique=False)
    op.create_index('ix_agendamentos_tenant_intervalo', 'agendamentos', ['tenant_id', 'inicio', 'fim'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agendamentos_tenant_intervalo', table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_tenant_id'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index(op.f('ix_usuarios_tenant_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # sa.Enum('DONO', 'ATENDENTE', name='papel') vira um TYPE nativo
    # no Postgres (nao existe em SQLite, por isso este bug so aparece
    # testando contra Postgres de verdade -- Etapa 5). Derrubar a
    # tabela usuarios NAO derruba o type; sem esta linha, um segundo
    # upgrade apos este downgrade falha com "type papel already
    # exists".
    sa.Enum(name='papel').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_servicos_tenant_id'), table_name='servicos')
    op.drop_table('servicos')
    op.drop_index(op.f('ix_clientes_tenant_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_table('tenants')
    # ### end Alembic commands ###
